package pattern;

/**
 * Enum of all allowed entries' types
 */
public enum EntryType {
    ARTICLE,BOOK,BOOKLET,INBOOK,INCOLLECTION,INPROCEEDINGS,MANUAL,MASTERSTHESIS,MISC,PHDTHESIS,TECHREPORT,UNPUBLISHED
}
